Use EulithWeb3 as context manager
Eulith/eulith-feature-test-scripts pull request #9
Opened 2023-10-31 22:09 UTC by ian-eulith

2023-11-01 03:42 UTC, kristian1108 requested changes

2023-11-01 03:42 UTC, kristian1108 commented on examples/gmx_limit_orders.py
> -    ew3 = EulithWeb3("https://arb-main.eulithrpc.com/v0", EULITH_TOKEN, construct_signing_middleware(wallet))
Do you know what happened to the spacing here? Was my IDE weird? I don't want to change the spacing standard in half the files here and not the others.

2023-11-01 14:01 UTC, ian-eulith commented on examples/gmx_limit_orders.py
> -    ew3 = EulithWeb3("https://arb-main.eulithrpc.com/v0", EULITH_TOKEN, construct_signing_middleware(wallet))
You mean the extra level of indentation? That's inherent to the `with` statement in Python. Only half the files are changed because half the files were already using `with`. You can check 'Hide whitespace' in GitHub while reviewing.

2023-11-15 23:21 UTC, kristian1108 approved these changes

2023-11-15 23:21 UTC, merged